/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CatalogModifierToggleOverrideType : Possible types of overrides for a CatalogModifier
/// Possible types of overrides for a CatalogModifier
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CatalogModifierToggleOverrideType {
    #[serde(rename = "YES")]
    Yes,
    #[serde(rename = "NO")]
    No,

}

impl std::fmt::Display for CatalogModifierToggleOverrideType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Yes => write!(f, "YES"),
            Self::No => write!(f, "NO"),
        }
    }
}

impl Default for CatalogModifierToggleOverrideType {
    fn default() -> CatalogModifierToggleOverrideType {
        Self::Yes
    }
}

